import './(styles)/global.css'
import Nav from './(components)/nav'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <Nav />
        <div className="container">
          <div className="columns is-centered">
            <div className="column is-full">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
